# Generated by Django 6.0.4 on 2026-04-30 13:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('date', models.DateField(verbose_name='Дата')),
                ('location', models.CharField(max_length=255, verbose_name='Место выполнения')),
                ('position', models.CharField(blank=True, max_length=255, verbose_name='Должность')),
                ('work_type', models.TextField(verbose_name='Вид работы')),
                ('instructions', models.TextField(verbose_name='Инструкции по ТБ')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('progress', 'В процессе'), ('done', 'Завершён'), ('closed', 'Закрыт')], default='draft', max_length=20, verbose_name='Статус')),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_orders', to=settings.AUTH_USER_MODEL, verbose_name='Старший наряда')),
                ('issuer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issued_orders', to=settings.AUTH_USER_MODEL, verbose_name='Выдал')),
            ],
            options={
                'verbose_name': 'Наряд',
                'verbose_name_plural': 'Наряды',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Brigade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('work_order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='brigade', to='workorders.workorder', verbose_name='Наряд')),
            ],
            options={
                'verbose_name': 'Бригада',
                'verbose_name_plural': 'Бригады',
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Создание'), ('update', 'Обновление'), ('delete', 'Удаление'), ('sign', 'Подписание'), ('close', 'Закрытие')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='workorders.workorder', verbose_name='Наряд')),
            ],
            options={
                'verbose_name': 'Запись аудита',
                'verbose_name_plural': 'Журнал аудита',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BrigadeMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_leader', models.BooleanField(default=False, verbose_name='Старший наряда')),
                ('brigade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='workorders.brigade', verbose_name='Бригада')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Член бригады',
                'verbose_name_plural': 'Члены бригады',
                'unique_together': {('brigade', 'user')},
            },
        ),
        migrations.CreateModel(
            name='Signature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('issuer', 'Выдал'), ('leader', 'Старший наряда'), ('worker', 'Работник')], max_length=20, verbose_name='Роль')),
                ('signed_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signatures', to='workorders.workorder', verbose_name='Наряд')),
            ],
            options={
                'verbose_name': 'Подпись',
                'verbose_name_plural': 'Подписи',
                'unique_together': {('work_order', 'user', 'role')},
            },
        ),
    ]
